"""
gen_exports.py - write pipeline/extractor/Generated.cs from a replay survey.

Each season ships its own build pieces, weapons and containers, and the parser only
decodes types it has a definition for. This reads a survey (data menu option S) and
writes one small definition per type, so the extractor captures them.

    python gen_exports.py <survey.json> [--parser-src <FortniteReplayDecompressor/src>]

--parser-src skips paths the parser itself defines at a level the extractor uses
(defining a path twice would stop the parser). Rebuild the extractor afterwards (option 1).
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "extractor" / "Generated.cs"
LEVELS = {"EventsOnly": 0, "Minimal": 1, "Normal": 2, "Full": 3, "Debug": 4, "Ignore": 5}


def parser_paths(src: Path) -> set[str]:
    """Paths the parser registers at Full or lower (those would clash with ours)."""
    found = set()
    for f in src.rglob("*.cs"):
        for m in re.finditer(r'NetFieldExportGroup\("([^"]+)"(?:,\s*(?:minimalParseMode:\s*)?ParseMode\.(\w+))?', f.read_text(errors="ignore")):
            if LEVELS.get(m.group(2) or "Normal", 2) <= LEVELS["Full"]:
                found.add(m.group(1))
    return found


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("survey")
    ap.add_argument("--parser-src")
    ap.add_argument("--out", default=str(OUT))
    a = ap.parse_args()
    s = json.loads(Path(a.survey).read_text(encoding="utf-8"))
    groups = [g for g in s["groups"] if not g["path"].endswith("ClassNetCache") and ":" not in g["path"]]
    skip = parser_paths(Path(a.parser_src)) if a.parser_src else set()
    kinds = {
        "BuildExport": [g["path"] for g in groups if "/ActorBlueprints/Player/" in g["path"] and "TeamIndex" in g["fields"]],
        "WeaponExport": [g["path"] for g in groups if "WeaponData" in g["fields"]],
        "ContainerExport": [g["path"] for g in groups if "bAlreadySearched" in g["fields"] and "SearchingPawn" in g["fields"]],
    }
    lines = [
        "// <auto-generated> by pipeline/python/gen_exports.py",
        f"// from survey {s.get('match_id')} ({s.get('branch')}). Re-generate when a new season adds types.",
        "using Unreal.Core.Attributes;",
        "using Unreal.Core.Models.Enums;",
        "",
    ]
    n = 0
    for base, paths in kinds.items():
        for p in sorted(set(paths) - skip):
            lines.append(f'[NetFieldExportGroup("{p}", ParseMode.Minimal)] public sealed class G{n:04d} : {base} {{ }}')
            n += 1
    Path(a.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {n} definitions to {a.out}: " + ", ".join(f"{len(set(v) - skip)} {k.replace('Export', '').lower()}s" for k, v in kinds.items())
          + (f" ({len(skip & {p for v in kinds.values() for p in v})} skipped: defined by the parser)" if skip else ""))


if __name__ == "__main__":
    main()
